name: CI - dhos-janitor-api

on:
  push:

env:
  USERNAME: ${{ github.actor }}
  REPO_BASE: ${{ github.repository_owner }}/dhos
  OWNER: ${{ github.repository_owner }}
  SERVICE: dhos-janitor-api
  FOLDER: .

jobs:
  build_and_push:
    name: Build and Push
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/build-and-push-image-to-ghcr
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          username: ${{ env.USERNAME }}
          service: ${{ env.SERVICE }}
          repo_base: ${{ env.REPO_BASE }}
          folder: ${{ env.FOLDER }}
          owner: ${{ env.OWNER }}
          dispatch_token: ${{ secrets.DISPATCH_TOKEN }}
